#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHELFFLOW_ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
SHELFFLOW_FALLBACK_MAVEN_REPO="${HOME}/Documents/maven本地仓库目录/repo"

: "${APP_ENV:=development}"

if [[ -f "${SHELFFLOW_ROOT_DIR}/.env" ]]; then
  set -a
  source "${SHELFFLOW_ROOT_DIR}/.env"
  set +a
fi

if [[ -f "${SHELFFLOW_ROOT_DIR}/.env.${APP_ENV}" ]]; then
  set -a
  source "${SHELFFLOW_ROOT_DIR}/.env.${APP_ENV}"
  set +a
fi

if [[ -f "${SHELFFLOW_ROOT_DIR}/.env.local" ]]; then
  set -a
  source "${SHELFFLOW_ROOT_DIR}/.env.local"
  set +a
fi

: "${SHELFFLOW_ADMIN_HOST:=127.0.0.1}"
: "${SHELFFLOW_ADMIN_PORT:=3000}"
: "${SHELFFLOW_USER_WEB_HOST:=127.0.0.1}"
: "${SHELFFLOW_USER_WEB_PORT:=3001}"
: "${SHELFFLOW_GATEWAY_HOST:=127.0.0.1}"
: "${SHELFFLOW_GATEWAY_PORT:=4010}"
: "${SHELFFLOW_AUTH_SERVICE_PORT:=4011}"
: "${SHELFFLOW_ADMIN_SERVICE_PORT:=4012}"
: "${SHELFFLOW_USER_SERVICE_PORT:=4013}"
: "${SHELFFLOW_LEGACY_BACKEND_HOST:=127.0.0.1}"
: "${SHELFFLOW_LEGACY_BACKEND_PORT:=8082}"
: "${SHELFFLOW_MYSQL_HOST:=127.0.0.1}"
: "${SHELFFLOW_MYSQL_PORT:=3306}"
: "${SHELFFLOW_REDIS_HOST:=127.0.0.1}"
: "${SHELFFLOW_REDIS_PORT:=6379}"
: "${SHELFFLOW_DOCKER_PROJECT:=shelfflow}"
: "${SHELFFLOW_INFRA_SERVICES:=mysql redis rabbitmq}"
: "${SHELFFLOW_INFRA_WAIT_TIMEOUT_SECONDS:=90}"
: "${SHELFFLOW_INFRA_TZ:=Asia/Shanghai}"
: "${SHELFFLOW_USER_SMOKE_OPEN_ID:=sf-user-ui-smoke}"
: "${SHELFFLOW_USER_SMOKE_NAME:=UI Smoke User}"
: "${SHELFFLOW_USER_SMOKE_PHONE:=13800138000}"
: "${SHELFFLOW_USER_SMOKE_PASSWORD:=ShelfFlow#2026}"
: "${LOG_LEVEL:=INFO}"
: "${API_PREFIX:=/api}"
: "${JWT_SECRET:=dev-shelfflow-jwt-secret-change-me}"
: "${JWT_EXPIRES_IN:=PT12H}"
: "${CORS_ALLOWED_ORIGINS:=http://127.0.0.1:3000}"
: "${DB_HOST:=${SHELFFLOW_MYSQL_HOST}}"
: "${DB_PORT:=${SHELFFLOW_MYSQL_PORT}}"
: "${DB_NAME:=shelfflow}"
: "${DB_USER:=root}"
: "${DB_PASSWORD:=root}"
: "${REDIS_HOST:=${SHELFFLOW_REDIS_HOST}}"
: "${REDIS_PORT:=${SHELFFLOW_REDIS_PORT}}"
: "${REDIS_PASSWORD:=}"
: "${REDIS_DATABASE:=1}"
if [[ -d "${SHELFFLOW_FALLBACK_MAVEN_REPO}" ]]; then
  : "${SHELFFLOW_MAVEN_REPO_LOCAL:=${SHELFFLOW_FALLBACK_MAVEN_REPO}}"
else
  : "${SHELFFLOW_MAVEN_REPO_LOCAL:=${SHELFFLOW_ROOT_DIR}/.m2/repository}"
fi

export SHELFFLOW_ROOT_DIR
export SHELFFLOW_ADMIN_HOST
export SHELFFLOW_ADMIN_PORT
export SHELFFLOW_USER_WEB_HOST
export SHELFFLOW_USER_WEB_PORT
export SHELFFLOW_GATEWAY_HOST
export SHELFFLOW_GATEWAY_PORT
export SHELFFLOW_AUTH_SERVICE_PORT
export SHELFFLOW_ADMIN_SERVICE_PORT
export SHELFFLOW_USER_SERVICE_PORT
export SHELFFLOW_LEGACY_BACKEND_HOST
export SHELFFLOW_LEGACY_BACKEND_PORT
export SHELFFLOW_MYSQL_HOST
export SHELFFLOW_MYSQL_PORT
export SHELFFLOW_REDIS_HOST
export SHELFFLOW_REDIS_PORT
export SHELFFLOW_DOCKER_PROJECT
export SHELFFLOW_INFRA_SERVICES
export SHELFFLOW_INFRA_WAIT_TIMEOUT_SECONDS
export SHELFFLOW_INFRA_TZ
export SHELFFLOW_USER_SMOKE_OPEN_ID
export SHELFFLOW_USER_SMOKE_NAME
export SHELFFLOW_USER_SMOKE_PHONE
export SHELFFLOW_USER_SMOKE_PASSWORD
export APP_ENV
export LOG_LEVEL
export API_PREFIX
export JWT_SECRET
export JWT_EXPIRES_IN
export CORS_ALLOWED_ORIGINS
export DB_HOST
export DB_PORT
export DB_NAME
export DB_USER
export DB_PASSWORD
export REDIS_HOST
export REDIS_PORT
export REDIS_PASSWORD
export REDIS_DATABASE
export SHELFFLOW_MAVEN_REPO_LOCAL

export SHELFFLOW_ADMIN_BASE_URL="${SHELFFLOW_ADMIN_BASE_URL:-http://${SHELFFLOW_ADMIN_HOST}:${SHELFFLOW_ADMIN_PORT}}"
export SHELFFLOW_USER_WEB_BASE_URL="${SHELFFLOW_USER_WEB_BASE_URL:-http://${SHELFFLOW_USER_WEB_HOST}:${SHELFFLOW_USER_WEB_PORT}}"
export SHELFFLOW_GATEWAY_BASE_URL="${SHELFFLOW_GATEWAY_BASE_URL:-http://${SHELFFLOW_GATEWAY_HOST}:${SHELFFLOW_GATEWAY_PORT}}"
export SHELFFLOW_AUTH_SERVICE_BASE_URL="${SHELFFLOW_AUTH_SERVICE_BASE_URL:-http://${SHELFFLOW_GATEWAY_HOST}:${SHELFFLOW_AUTH_SERVICE_PORT}}"
export SHELFFLOW_ADMIN_SERVICE_BASE_URL="${SHELFFLOW_ADMIN_SERVICE_BASE_URL:-http://${SHELFFLOW_GATEWAY_HOST}:${SHELFFLOW_ADMIN_SERVICE_PORT}}"
export SHELFFLOW_USER_SERVICE_BASE_URL="${SHELFFLOW_USER_SERVICE_BASE_URL:-http://${SHELFFLOW_GATEWAY_HOST}:${SHELFFLOW_USER_SERVICE_PORT}}"
export SHELFFLOW_LEGACY_BACKEND_BASE_URL="${SHELFFLOW_LEGACY_BACKEND_BASE_URL:-http://${SHELFFLOW_LEGACY_BACKEND_HOST}:${SHELFFLOW_LEGACY_BACKEND_PORT}}"
export AUTH_SERVICE_BASE_URL="${AUTH_SERVICE_BASE_URL:-${SHELFFLOW_AUTH_SERVICE_BASE_URL}}"
export ADMIN_SERVICE_BASE_URL="${ADMIN_SERVICE_BASE_URL:-${SHELFFLOW_ADMIN_SERVICE_BASE_URL}}"
export USER_SERVICE_BASE_URL="${USER_SERVICE_BASE_URL:-${SHELFFLOW_USER_SERVICE_BASE_URL}}"
