CREATE TABLE IF NOT EXISTS admin_order_event_inbox (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    event_id BIGINT NOT NULL,
    message_id VARCHAR(80),
    order_id BIGINT NOT NULL,
    order_number VARCHAR(64),
    user_id BIGINT,
    event_type VARCHAR(32) NOT NULL,
    actor_type VARCHAR(16),
    actor_id BIGINT,
    from_status INT,
    to_status INT,
    from_pay_status INT,
    to_pay_status INT,
    total_amount DECIMAL(10, 2),
    item_count INT,
    note VARCHAR(255),
    routing_key VARCHAR(128),
    status VARCHAR(16) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    failure_reason VARCHAR(512),
    event_time DATETIME,
    received_time DATETIME NOT NULL,
    processed_time DATETIME,
    create_time DATETIME NOT NULL,
    update_time DATETIME NOT NULL,
    UNIQUE KEY uk_admin_order_event_inbox_event_id (event_id),
    KEY idx_admin_order_event_inbox_order_number (order_number),
    KEY idx_admin_order_event_inbox_status_time (status, received_time),
    KEY idx_admin_order_event_inbox_event_type (event_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='管理端订单事件消费 inbox';
